import LegalLayout from '../components/LegalLayout'

function Section({ heading, children }) {
  return (
    <section>
      <h2 className="font-display text-xl font-semibold text-ink-900 dark:text-white">{heading}</h2>
      <div className="mt-3 space-y-3">{children}</div>
    </section>
  )
}

export default function Terms() {
  return (
    <LegalLayout title="Terms of Use" updated="September 2026">
      <p>
        These Terms of Use ("Terms") govern access to and use of Oudaa (the
        "Service"), software for managing residential community finances
        including fees, funds, payments, expenses and related records. By
        creating an account or using the Service, you agree to these Terms.
      </p>

      <Section heading="1. Accounts and roles">
        <p>
          The Service has two kinds of accounts: committee/admin accounts,
          which manage a community, and resident accounts, which belong to
          one. Admin accounts are responsible for the accuracy of the
          community and resident data they enter, and for how resident
          accounts within their community are created and managed.
        </p>
      </Section>

      <Section heading="2. Acceptable use">
        <p>You agree not to:</p>
        <ul className="list-disc space-y-1.5 pl-5">
          <li>Use the Service to enter false financial records or misrepresent a community's funds.</li>
          <li>Attempt to access another community's data, or another user's account, without authorization.</li>
          <li>Interfere with or disrupt the Service, including attempting to bypass security or rate limits.</li>
          <li>Use the Service for any unlawful purpose or in violation of applicable regulations governing community associations or financial recordkeeping in your jurisdiction.</li>
        </ul>
      </Section>

      <Section heading="3. Financial data and payment verification">
        <p>
          The Service may check self-reported payments against bank
          transaction data through a third-party verification provider where
          enabled. This feature is provided to reduce manual reconciliation
          work; it is not a guarantee against fraud, and admins remain
          responsible for reviewing flagged or unverifiable payments.
        </p>
        <p>
          Oudaa is a record-keeping and workflow tool. It does not hold,
          transmit, or move community funds itself, and is not a bank,
          payment processor, or financial institution.
        </p>
      </Section>

      <Section heading="4. Content you submit">
        <p>
          You retain ownership of the data and files (including receipts and
          documents) you or your community submit to the Service. You grant
          us the right to store, process and display that content as needed
          to operate the Service on your behalf — for example, extracting
          data from a receipt image, or including a record in a report.
        </p>
      </Section>

      <Section heading="5. Availability">
        <p>
          We aim to keep the Service available and reliable but do not
          guarantee uninterrupted access. Features such as email delivery
          and bank payment verification depend on third-party providers and
          may be temporarily degraded if those providers are unavailable;
          the Service is designed to fail safely (e.g. continuing to work
          with email or verification temporarily disabled) rather than
          block core functionality.
        </p>
      </Section>

      <Section heading="6. Termination">
        <p>
          A community admin may stop using the Service at any time. We may
          suspend or terminate access for accounts that violate these Terms,
          misuse the Service, or pose a security risk to other communities
          on the platform.
        </p>
      </Section>

      <Section heading="7. Disclaimer of warranties">
        <p>
          The Service is provided "as is" without warranties of any kind,
          express or implied. We do not warrant that the Service will be
          error-free, that financial figures generated by it are free of
          input error, or that payment verification will catch every
          discrepancy.
        </p>
      </Section>

      <Section heading="8. Limitation of liability">
        <p>
          To the extent permitted by law, Oudaa and its operators are not
          liable for indirect, incidental or consequential damages arising
          from use of the Service, including disputes over community funds
          that arise from data entered by a community's own admins or
          residents.
        </p>
      </Section>

      <Section heading="9. Changes to these Terms">
        <p>
          We may update these Terms from time to time. Continued use of the
          Service after an update constitutes acceptance of the revised
          Terms. Material changes will be reflected by updating the date at
          the top of this page.
        </p>
      </Section>

      <Section heading="10. Contact">
        <p>
          Questions about these Terms can be sent to{' '}
          <a href="mailto:support@oudaa.app" className="text-brand-600 hover:underline dark:text-brand-300">
            support@oudaa.app
          </a>
          .
        </p>
      </Section>
    </LegalLayout>
  )
}
